- hosts: master
  become: yes
  #gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: TCP port 6443 on master is reachable from worker
      wait_for: "host=kube-control port=6443 timeout=1"

    - name: join cluster
      shell: "kubeadm join 192.168.1.101:6443 --token nzsove.77hxktfrsn5zjl6o --discovery-token-ca-cert-hash sha256:d56cdc9e8bdf822f33a82a2200d18aac803627d2af8fa3d60ba142be4a52cc42  >> node_joined.log"
      args:
        chdir: /home/jackarian
        creates: node_joined.log
